# Generated by Django 5.1.4 on 2025-01-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='courriers/', verbose_name='Fichier'),
        ),
    ]
