# Generated by Django 5.1.4 on 2025-02-26 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_client_created_by_alter_client_updated_by_and_more'),
        ('courrier', '0002_courrier_fichier'),
        ('document', '0019_alter_opportunite_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourrierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('EDIT', 'Modification'), ('SEND', 'Envoi'), ('RECEIVE', 'Réception'), ('PROCESS', 'Traitement'), ('ARCHIVE', 'Archivage'), ('NOTE', 'Annotation')], max_length=10)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historique de courrier',
                'verbose_name_plural': 'Historiques de courriers',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AlterModelOptions(
            name='courrier',
            options={'ordering': ['-date_creation', 'reference'], 'verbose_name': 'Courrier', 'verbose_name_plural': 'Courriers'},
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_envoi',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi"),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entrant'), ('OUT', 'Sortant')], default='OUT', max_length=3, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='est_urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='objet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objet'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='statut',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('RECEIVED', 'Reçu'), ('ARCHIVED', 'Archivé'), ('PENDING', 'En attente'), ('PROCESSED', 'Traité')], default='DRAFT', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='courriers/%Y/%m/', verbose_name='Fichier'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['reference'], name='courrier_co_referen_04d977_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['client'], name='courrier_co_client__ffc1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['date_creation'], name='courrier_co_date_cr_39f348_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['statut'], name='courrier_co_statut_d9ac49_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['direction'], name='courrier_co_directi_eb80da_idx'),
        ),
        migrations.AddField(
            model_name='courrierhistory',
            name='courrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='courrier.courrier'),
        ),
        migrations.AddField(
            model_name='courrierhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
