# Generated by Django 5.1.4 on 2025-02-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_client_created_by_alter_client_updated_by_and_more'),
        ('courrier', '0003_courrierhistory_alter_courrier_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriers', to='client.client', verbose_name='Client'),
        ),
    ]
