# Generated by Django 5.1.4 on 2025-03-12 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres_app', '0006_offre_fichier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, help_text="Référence unique de l'affaire (générée automatiquement)", max_length=50, unique=True)),
                ('sequence_number', models.PositiveIntegerField(default=0, editable=False, help_text='Numéro de séquence pour la génération de référence')),
                ('doc_type', models.CharField(default='AFF', editable=False, help_text='Type de document (AFF pour Affaire)', max_length=3)),
                ('date_debut', models.DateTimeField(help_text="Date de début de l'affaire", verbose_name='Date de début')),
                ('date_fin_prevue', models.DateTimeField(blank=True, help_text="Date de fin prévue pour l'affaire", null=True, verbose_name='Date de fin prévue')),
                ('date_fin_reelle', models.DateTimeField(blank=True, help_text="Date de fin réelle de l'affaire (renseignée à la clôture)", null=True, verbose_name='Date de fin réelle')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text="Date de dernière modification de l'enregistrement", verbose_name='Dernière modification')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validée'), ('EN_COURS', 'En cours'), ('EN_PAUSE', 'En pause'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='BROUILLON', help_text="État actuel de l'affaire", max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, help_text="Notes internes concernant l'affaire", verbose_name='Notes')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, help_text="Montant total de l'affaire (HT)", max_digits=10, verbose_name='Montant total')),
                ('montant_facture', models.DecimalField(decimal_places=2, default=0, help_text='Montant total facturé (HT)', max_digits=10, verbose_name='Montant facturé')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, help_text='Montant total payé (HT)', max_digits=10, verbose_name='Montant payé')),
                ('created_by', models.ForeignKey(blank=True, help_text="Utilisateur ayant créé l'affaire", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('offre', models.OneToOneField(help_text='Offre acceptée qui a généré cette affaire', on_delete=django.db.models.deletion.CASCADE, related_name='affaire', to='offres_app.offre')),
                ('responsable', models.ForeignKey(blank=True, help_text="Utilisateur responsable de l'affaire", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_gerees', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Affaire',
                'verbose_name_plural': 'Affaires',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['reference'], name='affaires_ap_referen_3ef5bc_idx'), models.Index(fields=['statut'], name='affaires_ap_statut_29eea3_idx'), models.Index(fields=['date_creation'], name='affaires_ap_date_cr_6bec32_idx')],
            },
        ),
    ]
