# Generated by Django 5.1.4 on 2025-03-12 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date de début de l'affaire", verbose_name='Date de début'),
        ),
    ]
