# Generated by Django 5.1.4 on 2025-04-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires_app', '0003_remove_affaire_created_by_affaire_createur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='date_annulation',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'affaire a été annulée", null=True, verbose_name="Date d'annulation"),
        ),
        migrations.AddField(
            model_name='affaire',
            name='date_debut_effective',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'affaire a réellement commencé", null=True, verbose_name='Date de début effective'),
        ),
        migrations.AddField(
            model_name='affaire',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'affaire a été validée", null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='affaire',
            name='raison_annulation',
            field=models.TextField(blank=True, help_text="Raison pour laquelle l'affaire a été annulée", null=True, verbose_name="Raison d'annulation"),
        ),
    ]
