# Generated by Django 5.1.4 on 2025-04-13 00:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires_app', '0004_affaire_date_annulation_affaire_date_debut_effective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='montant_facture',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant total facturé (HT)', max_digits=20, verbose_name='Montant facturé'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant total payé (HT)', max_digits=20, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Montant total de l'affaire (HT)", max_digits=20, verbose_name='Montant total'),
        ),
    ]
