# Generated by Django 5.1.4 on 2025-02-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_contact_site_alter_contact_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source'),
        ),
    ]
