# Generated by Django 5.1.4 on 2025-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_contact_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='valide',
            field=models.BooleanField(default=True, verbose_name='Valide'),
        ),
    ]
