# Generated by Django 5.1.4 on 2025-02-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_contact_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='categorie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
