# Generated by Django 5.1.4 on 2025-02-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_categorie_client_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='s_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
