# Generated by Django 5.1.4 on 2025-04-17 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_client_created_by_alter_client_updated_by_and_more'),
        ('document', '0028_delete_statuschange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('couleur', models.CharField(blank=True, help_text="Code couleur pour l'interface", max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='date_conversion_client',
            field=models.DateField(blank=True, help_text='Date de conversion de prospect à client', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='est_client',
            field=models.BooleanField(default=False, help_text="Indique si l'entreprise est un client actif"),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('statut_workflow', models.CharField(choices=[('DEMANDE', 'Demande en cours'), ('EN_REVUE', 'En cours de revue'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('EXPIRE', 'Expiré'), ('RENOUVELLEMENT', 'En attente de renouvellement')], default='DEMANDE', max_length=20)),
                ('date_statut', models.DateField(auto_now=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='client.client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_crees', to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='document.entity')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'entite', 'date_debut')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='entites_agreement',
            field=models.ManyToManyField(blank=True, help_text='Entités avec lesquelles cette entreprise a un accord', through='client.Agreement', to='document.entity'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('est_rendez_vous', models.BooleanField(default=False)),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('date_relance', models.DateField(blank=True, null=True)),
                ('relance_effectuee', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='client.contact')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_creees', to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='document.entity')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='client.client')),
                ('type_interaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.typeinteraction')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
