# Generated by Django 5.1.4 on 2025-04-17 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_typeinteraction_client_date_conversion_client_and_more'),
        ('document', '0028_delete_statuschange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Agreement', 'verbose_name_plural': 'Agreements'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-date'], 'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Région', 'verbose_name_plural': 'Régions'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='typeinteraction',
            options={'verbose_name': "Type d'interaction", 'verbose_name_plural': "Types d'interactions"},
        ),
        migrations.AlterModelOptions(
            name='ville',
            options={'verbose_name': 'Ville', 'verbose_name_plural': 'Villes'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='agreer',
            new_name='agree',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='entreprise',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='agreement_fournisseur',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='cree_par',
        ),
        migrations.AddField(
            model_name='interaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ville',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(choices=[('PME', 'Petite et Moyenne Entreprise'), ('TPE', 'Très Petite Entreprise'), ('PE', 'Petite Entreprise'), ('GE', 'Grande Entreprise')], max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='c_num',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='est_client',
            field=models.BooleanField(default=False, help_text="Indique si l'entreprise est un client actif", verbose_name='Est client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='s_num',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typeinteraction',
            name='couleur',
            field=models.CharField(blank=True, help_text="Code couleur pour l'interface (ex: #FF5733)", max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('nom', 'pays')},
        ),
        migrations.AlterUniqueTogether(
            name='ville',
            unique_together={('nom', 'region')},
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['client'], name='client_agre_client__d34d54_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['entite'], name='client_agre_entite__899e35_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['date_debut'], name='client_agre_date_de_4e3db2_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['date_fin'], name='client_agre_date_fi_1dc716_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['statut_workflow'], name='client_agre_statut__9faa7d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nom'], name='client_clie_nom_f23534_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['c_num'], name='client_clie_c_num_06939f_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['est_client'], name='client_clie_est_cli_a9c411_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['client'], name='client_cont_client__f94c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['site'], name='client_cont_site_id_57e87c_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['nom', 'prenom'], name='client_cont_nom_90fd95_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='client_cont_email_d63cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['date'], name='client_inte_date_161c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['contact'], name='client_inte_contact_d12a80_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['client'], name='client_inte_client__36be39_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['type_interaction'], name='client_inte_type_in_9051db_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['date_relance'], name='client_inte_date_re_396411_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['client'], name='client_site_client__fcbaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['s_num'], name='client_site_s_num_9ac4fc_idx'),
        ),
    ]
