# Generated by Django 5.1.4 on 2025-04-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_agreement_options_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(choices=[('PME', 'Petite et Moyenne Entreprise'), ('TPE', 'Très Petite Entreprise'), ('PE', 'Petite Entreprise'), ('GE', 'Grande Entreprise')], max_length=3),
        ),
    ]
