# Generated by Django 5.1.4 on 2025-01-22 08:31

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_rapport_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationformation',
            name='statut',
            field=django_fsm.FSMField(default='BROUILLON', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=django_fsm.FSMField(default='BROUILLON', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=django_fsm.FSMField(default='BROUILLON', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='statut',
            field=django_fsm.FSMField(default='BROUILLON', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='statut',
            field=django_fsm.FSMField(default='BROUILLON', max_length=50, protected=True),
        ),
    ]
