# Generated by Django 5.1.4 on 2025-01-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_attestationformation_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationformation',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=20),
        ),
    ]
