# Generated by Django 5.1.4 on 2025-01-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_category_created_at_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenttype',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.contenttype'),
        ),
    ]
