# Generated by Django 5.1.4 on 2025-01-31 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('document', '0007_alter_auditlog_content_type_delete_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='attestationformation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.RemoveField(
            model_name='site',
            name='client',
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='client.client'),
        ),
        migrations.RemoveField(
            model_name='site',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='site',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='rapport',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.site'),
        ),
        migrations.AddField(
            model_name='offre',
            name='produits',
            field=models.ManyToManyField(to='document.product'),
        ),
        migrations.RemoveField(
            model_name='offre',
            name='produit',
        ),
        migrations.AlterField(
            model_name='offre',
            name='sites',
            field=models.ManyToManyField(to='client.site'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.AddField(
            model_name='offre',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='document.product'),
            preserve_default=False,
        ),
    ]
