# Generated by Django 5.1.4 on 2025-01-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_offre_client_alter_attestationformation_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='attestationformation',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='offre',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
