# Generated by Django 5.1.4 on 2025-02-06 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_affaire_fichier_attestationformation_fichier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='site',
        ),
        migrations.AddField(
            model_name='attestationformation',
            name='rapport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='document.rapport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapport',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
