# Generated by Django 5.1.4 on 2025-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_affaire_created_by_attestationformation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='participants/'),
        ),
    ]
