# Generated by Django 5.1.4 on 2025-02-20 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_categorie_alter_client_categorie'),
        ('document', '0013_offre_contact_offre_montant_offre_relance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documents', to='client.client'),
        ),
        migrations.AlterField(
            model_name='attestationformation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documents', to='client.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documents', to='client.client'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documents', to='client.client'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documents', to='client.client'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documents', to='client.client'),
        ),
    ]
