# Generated by Django 5.1.4 on 2025-02-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_categorie_alter_client_categorie'),
        ('document', '0015_alter_affaire_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='client.client'),
        ),
        migrations.AlterField(
            model_name='attestationformation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='client.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='client.client'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='client.client'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='client.client'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='client.client'),
        ),
    ]
