# Generated by Django 5.1.4 on 2025-02-25 09:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_client_created_by_alter_client_updated_by_and_more'),
        ('document', '0017_alter_affaire_created_by_alter_affaire_entity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('sequence_number', models.IntegerField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PROSPECT', 'Prospect'), ('QUALIFICATION', 'Qualification'), ('PROPOSITION', 'Proposition'), ('NEGOCIATION', 'Négociation'), ('GAGNEE', 'Gagnée'), ('PERDUE', 'Perdue')], default='PROSPECT', max_length=20)),
                ('montant_estime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('probabilite', models.IntegerField(default=0, help_text='Probabilité de conversion en %')),
                ('description', models.TextField(blank=True, null=True)),
                ('besoins_client', models.TextField(blank=True, null=True)),
                ('relance', models.DateTimeField(blank=True, help_text='Date de la prochaine relance', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunites', to='client.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunites', to='client.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='document.entity')),
                ('produit_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunites_principales', to='document.product')),
                ('produits', models.ManyToManyField(related_name='opportunites', to='document.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
