# Generated by Django 5.1.4 on 2025-02-25 19:54

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_opportunite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunite',
            name='statut',
            field=django_fsm.FSMField(choices=[('PROSPECT', 'Prospect'), ('QUALIFICATION', 'Qualification'), ('PROPOSITION', 'Proposition'), ('NEGOCIATION', 'Négociation'), ('GAGNEE', 'Gagnée'), ('PERDUE', 'Perdue')], default='PROSPECT', max_length=20),
        ),
    ]
