# Generated by Django 5.1.4 on 2025-03-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_remove_offre_client_remove_offre_contact_and_more'),
        ('offres_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='offre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affaire', to='offres_app.offre'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='offre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proforma', to='offres_app.offre'),
        ),
        migrations.DeleteModel(
            name='Offre',
        ),
    ]
