# Generated by Django 5.1.4 on 2025-03-12 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires_app', '0001_initial'),
        ('document', '0021_alter_affaire_offre_alter_proforma_offre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='affaires_app.affaire'),
        ),
        migrations.AlterField(
            model_name='attestationformation',
            name='affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='affaires_app.affaire'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='affaires_app.affaire'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='affaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='affaires_app.affaire'),
        ),
        migrations.DeleteModel(
            name='Affaire',
        ),
    ]
