# Generated by Django 5.1.4 on 2025-03-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_alter_formation_affaire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proforma',
        ),
    ]
