# Generated by Django 5.1.4 on 2025-03-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0023_delete_proforma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
