# Generated by Django 5.1.4 on 2025-04-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0025_statuschange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opportunite',
        ),
    ]
