# Generated by Django 5.1.4 on 2025-04-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0027_useractionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusChange',
        ),
    ]
