# Generated by Django 5.1.4 on 2025-04-17 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0028_delete_statuschange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Departement',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='departement',
        ),
    ]
