# Generated by Django 5.1.4 on 2025-04-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunites_app', '0002_opportunite_commantaire_opportunite_responsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunite',
            old_name='commantaire',
            new_name='commentaire',
        ),
    ]
