# Generated by Django 5.1.4 on 2025-03-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='relance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de relance'),
        ),
    ]
