# Generated by Django 5.1.4 on 2025-03-18 13:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affaires_app', '0002_alter_affaire_date_debut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Référence')),
                ('sequence_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de séquence')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_emission', models.DateTimeField(blank=True, null=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateTimeField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée'), ('IMPAYEE', 'Impayée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('19.25'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Montant TTC')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Montant payé')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='factures/', verbose_name='Fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création dans le système')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('affaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='affaires_app.affaire', verbose_name='Affaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_creation'],
            },
        ),
    ]
