# Generated by Django 5.1.4 on 2025-04-12 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ancien_statut', models.CharField(max_length=30)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de changement de statut',
                'verbose_name_plural': 'Historique des changements de statut',
                'ordering': ['-date_changement'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='status_trak_content_0f5f01_idx'), models.Index(fields=['date_changement'], name='status_trak_date_ch_a1da08_idx'), models.Index(fields=['nouveau_statut'], name='status_trak_nouveau_7e34b2_idx'), models.Index(fields=['utilisateur'], name='status_trak_utilisa_29685d_idx')],
            },
        ),
    ]
