# Generated by Django 5.1.4 on 2025-03-10 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0011_alter_client_created_by_alter_client_updated_by_and_more'),
        ('document', '0020_remove_offre_client_remove_offre_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('GAGNE', 'Gagné'), ('PERDU', 'Perdu')], default='BROUILLON', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('relance', models.DateTimeField(blank=True, help_text="Date de la prochaine relance si l'offre n'est pas encore gagnée", null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='client.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='client.contact')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='document.entity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OffreProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('remise', models.FloatField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres_app.offre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.product')),
            ],
            options={
                'unique_together': {('offre', 'produit')},
            },
        ),
        migrations.AddField(
            model_name='offre',
            name='produits',
            field=models.ManyToManyField(related_name='offres', through='offres_app.OffreProduit', to='document.product'),
        ),
    ]
