# Generated by Django 5.1.4 on 2025-03-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='montant',
        ),
    ]
