# Generated by Django 5.1.4 on 2025-03-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres_app', '0002_remove_offre_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
