# Generated by Django 5.1.4 on 2025-03-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres_app', '0003_offre_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreproduit',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='offreproduit',
            name='remise',
        ),
        migrations.AlterField(
            model_name='offreproduit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
