# Generated by Django 5.1.4 on 2025-03-11 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_alter_affaire_offre_alter_proforma_offre_and_more'),
        ('offres_app', '0004_remove_offreproduit_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_unique', to='document.product'),
        ),
    ]
