# Generated by Django 5.1.4 on 2025-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres_app', '0005_offre_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='offres/'),
        ),
    ]
