# Generated by Django 5.1.4 on 2025-03-12 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_alter_formation_affaire_and_more'),
        ('offres_app', '0006_offre_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreproduit',
            name='prix_unitaire',
        ),
        migrations.AlterField(
            model_name='offre',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offre',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offres_unique', to='document.product'),
            preserve_default=False,
        ),
    ]
