# Generated by Django 5.1.4 on 2025-03-26 07:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0025_statuschange'),
        ('offres_app', '0008_alter_offre_montant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offre',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Offre commerciale', 'verbose_name_plural': 'Offres commerciales'},
        ),
        migrations.AlterModelOptions(
            name='offreproduit',
            options={'verbose_name': "Produit de l'offre", 'verbose_name_plural': "Produits de l'offre"},
        ),
        migrations.RemoveField(
            model_name='offre',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='produit',
        ),
        migrations.AddField(
            model_name='offre',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='offre',
            name='dates_statuts',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dates des statuts'),
        ),
        migrations.AddField(
            model_name='offre',
            name='modificateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='offre',
            name='produit_principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offres_principal', to='document.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offreproduit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='offreproduit',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('EN_NEGOCIATION', 'En négociation'), ('GAGNE', 'Gagné'), ('PERDU', 'Perdu')], default='BROUILLON', max_length=30),
        ),
        migrations.AlterField(
            model_name='offre',
            name='user',
            field=models.ForeignKey(help_text="Utilisateur qui a créé l'offre initialement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offreproduit',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_produits', to='offres_app.offre'),
        ),
    ]
