# Generated by Django 5.1.4 on 2025-04-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres_app', '0009_alter_offre_options_alter_offreproduit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offre',
            options={'ordering': ['date_creation'], 'verbose_name': 'Offre commerciale', 'verbose_name_plural': 'Offres commerciales'},
        ),
        migrations.AddField(
            model_name='offre',
            name='date_cloture',
            field=models.DateField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='offre',
            name='date_envoi',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi"),
        ),
        migrations.AddField(
            model_name='offre',
            name='date_validation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='relance',
            field=models.DateField(blank=True, help_text="Date de la prochaine relance si l'offre n'est pas encore gagnée", null=True),
        ),
    ]
