# Generated by Django 5.1.4 on 2025-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres_app', '0010_alter_offre_options_offre_date_cloture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='relance',
            field=models.DateTimeField(blank=True, help_text="Date de la prochaine relance si l'offre n'est pas encore gagnée", null=True),
        ),
    ]
